<?php
/*
* Implementation of the hook_user_login().
*/
function custom_user_login() {
	global $user;
	drupal_set_message("Hello ".$user->name);
}
/*
* Implementation of login_form_alter().
*/
function custom_form_alter(&$form, &$form_state, $form_id) {
	if($form_id == 'user_login' || $form_id == 'user_login_block') {
		drupal_set_message("Login to enter to the website.");
	}
}

function custom_init() {
  $method = $_SERVER['REQUEST_METHOD'];

  if (isset($_SERVER['HTTP_ORIGIN'])) {
    drupal_add_http_header('Access-Control-Allow-Origin', $_SERVER['HTTP_ORIGIN']);
  }
  if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS'])) {
    drupal_add_http_header('Access-Control-Allow-Headers', $_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']);
  }
  if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD'])) {
    drupal_add_http_header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  }
  if ($method == 'OPTIONS') {
    exit;
  }
}
?>
